### ISSUE TITLE
Cannot change font

### ISSUE THREAD

**Issue by pantlmn** [czcorpus/InterText_editor#1]
I cannot change font: I see the dialog with all fonts, but changing font doesn't change it in the viewer.
InterText 1.6 for Mac
OSX 10.12.3 (Sierra)

**Comment by wanthalf** [comment]
Actually, after selecting a new font and closing the font dialog, the settings dialog just disappears BEHIND the main window. If you bring it back to the front and confirm the new settings, it works.
I will try to fix this bad behaviour properly and release as version 1.6.1.

**Comment by wanthalf** [comment]
Fixed in release 1.6.1.
