### ISSUE TITLE
TEI namespace

### ISSUE THREAD

**Issue by ngawangtrinley** [czcorpus/InterText_editor#4]
Is there a reason you don't declare the TEI namespace in the 3 TEI files?

Something like:
```
<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:tei="http://www.tei-c.org/ns/1.0">
   <text>
       
    </text>
</TEI>
```
...or:
```
<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
   <text>
       
    </text>
</TEI>
```

**Comment by wanthalf** [comment]
The files are not fully compliant TEI documents anyway. TEI requires a minimal header with some metadata, such as name of the text, author, origin, etc. You can also import fully compliant TEI documents and align them in InterText, but the application is not meant to create full TEI documents from plain text. This is beyond the scope of InterText to provide an interface for, but you can easily adapt it to your needs and edit the templates or the resulting exported files if you want to.

**Comment by ngawangtrinley** [comment]
ok, that makes sense. thanks
