### ISSUE TITLE
Error presented when installing intertext editor.exe

### ISSUE THREAD

**Issue by applediet** [czcorpus/InterText_editor#6]
When installing intertext editor.exe, the following msg poped up: Network error while downloading 'https://wanthalf.saga.cz/repository/intertext/windows/Updates.xml 776810394': SSL handshake failed.

Please kindly advise. Thank you

**Comment by ngawangtrinley** [comment]
Error reproduced here too on Windows 11, 64 bits.

![image](https://user-images.githubusercontent.com/17675331/182749812-e7198da1-fae3-47ae-a6d0-8c1dac28de37.png)

It might be related to your website not using https, does your certificate need to be renewed?
![image](https://user-images.githubusercontent.com/17675331/182750079-0c70087f-f7bb-499d-a962-386ec5023e46.png)

**Comment by wanthalf** [comment]
Should be fixed now. The certificate update on the wesite got stuck somehow, again. Thanks for notice!
